name: Deploy Whoami

on:
    push:
        branches: [ "main" ]
        paths:
        - 'whoami/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Validate
              run: cd whoami && docker-compose config --quiet
            
            - name: Deploy
              run: echo "Deploying Whoami"