name: Deploy Whoami

on:
    push:
        branches: [ "main" ]
        paths:
        - 'whoami/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Deploy
              run: |
                rsync -avz --del whoami ${{ secrets.HOST }}:${{ secrets.REMOTE_DIR }}/
                ssh ${{ secrets.HOST }} "\
                    cd ${{ secrets.REMOTE_DIR }}/whoami && \
                    docker compose up -d --force-recreate \
                    "