name: Deploy Whoami

on:
    push:
        branches: [ "main" ]
        paths:
        - 'whoami/**'
    workflow_dispatch:

env:
    HOST: ${{ secrets.HOST }}
    USERNAME: ${{ secrets.USERNAME }}
    REMOTE_DIR: ${{ secrets.REMOTE_DIR }}

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Deploy
              run: |
                rsync -avz --del whoami $USERNAME@$HOST:$REMOTE_DIR/
                ssh $USERNAME@$HOST "cd $REMOTE_DIR/whoami && docker compose up -d --force-recreate"