name: Deploy Whoami

on:
    push:
        branches: [ "main" ]
        paths:
        - 'whoami/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Validate
              run: cd whoami && docker compose config --quiet
            
            - name: Deploy
              run: |
                scp -r whoami/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.REMOTE_DIR }}/whoami
                ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ${{ secrets.REMOTE_DIR }}/whoami && docker compose up -d"